#define STRINGIZE_INNER(value) #value
#define STRINGIZE(value) STRINGIZE_INNER(value)
STRINGIZE_INNER(__LINE__)
STRINGIZE(__LINE__)
STRINGIZE(__FILE__)
STRINGIZE(__CPPGM__)
#define CURRENT_LINE __LINE__
STRINGIZE(CURRENT_LINE)
#line 40 "virtual.cc"
STRINGIZE(__LINE__)
STRINGIZE(__FILE__)
