#pragma once

#include <cstdint>
#include <string>

namespace cppgm
{
namespace hosted_builtin
{

enum TypeTraitKind
{
	TYPE_TRAIT_NONE,
	TYPE_TRAIT_ARRAY_RANK,
	TYPE_TRAIT_HAS_NOTHROW_COPY,
	TYPE_TRAIT_HAS_TRIVIAL_CONSTRUCTOR,
	TYPE_TRAIT_HAS_VIRTUAL_DESTRUCTOR,
	TYPE_TRAIT_IS_ABSTRACT,
	TYPE_TRAIT_IS_AGGREGATE,
	TYPE_TRAIT_IS_ASSIGNABLE,
	TYPE_TRAIT_IS_BASE_OF,
	TYPE_TRAIT_IS_CLASS,
	TYPE_TRAIT_IS_COMPLETE_OR_UNBOUNDED,
	TYPE_TRAIT_IS_CONSTRUCTIBLE,
	TYPE_TRAIT_IS_CONVERTIBLE,
	TYPE_TRAIT_IS_DESTRUCTIBLE,
	TYPE_TRAIT_IS_EMPTY,
	TYPE_TRAIT_IS_ENUM,
	TYPE_TRAIT_IS_FINAL,
	TYPE_TRAIT_IS_FLOATING_POINT,
	TYPE_TRAIT_IS_FUNCTION,
	TYPE_TRAIT_IS_INTEGRAL,
	TYPE_TRAIT_IS_INVOCABLE,
	TYPE_TRAIT_IS_LITERAL_TYPE,
	TYPE_TRAIT_IS_MEMBER_FUNCTION_POINTER,
	TYPE_TRAIT_IS_MEMBER_OBJECT_POINTER,
	TYPE_TRAIT_IS_MEMBER_POINTER,
	TYPE_TRAIT_IS_NOTHROW_ASSIGNABLE,
	TYPE_TRAIT_IS_NOTHROW_CONSTRUCTIBLE,
	TYPE_TRAIT_IS_NOTHROW_INVOCABLE,
	TYPE_TRAIT_IS_POD,
	TYPE_TRAIT_IS_ARRAY,
	TYPE_TRAIT_IS_BOUNDED_ARRAY,
	TYPE_TRAIT_IS_UNBOUNDED_ARRAY,
	TYPE_TRAIT_IS_COMPOUND,
	TYPE_TRAIT_IS_CONST,
	TYPE_TRAIT_IS_VOLATILE,
	TYPE_TRAIT_IS_VOID,
	TYPE_TRAIT_IS_OBJECT,
	TYPE_TRAIT_IS_ARITHMETIC,
	TYPE_TRAIT_IS_FUNDAMENTAL,
	TYPE_TRAIT_IS_LVALUE_REFERENCE,
	TYPE_TRAIT_IS_RVALUE_REFERENCE,
	TYPE_TRAIT_IS_REFERENCEABLE,
	TYPE_TRAIT_IS_UNSIGNED,
	TYPE_TRAIT_IS_POINTER,
	TYPE_TRAIT_IS_POLYMORPHIC,
	TYPE_TRAIT_IS_REFERENCE,
	TYPE_TRAIT_IS_SAME,
	TYPE_TRAIT_IS_SCALAR,
	TYPE_TRAIT_IS_SIGNED,
	TYPE_TRAIT_IS_STANDARD_LAYOUT,
	TYPE_TRAIT_IS_TRIVIAL,
	TYPE_TRAIT_IS_TRIVIALLY_ASSIGNABLE,
	TYPE_TRAIT_IS_TRIVIALLY_CONSTRUCTIBLE,
	TYPE_TRAIT_IS_TRIVIALLY_COPYABLE,
	TYPE_TRAIT_IS_TRIVIALLY_DESTRUCTIBLE,
	TYPE_TRAIT_IS_UNION,
	TYPE_TRAIT_REFERENCE_BINDS_TO_TEMPORARY,
	TYPE_TRAIT_REFERENCE_CONSTRUCTS_FROM_TEMPORARY
};

enum TypeTransformKind
{
	TYPE_TRANSFORM_NONE,
	TYPE_TRANSFORM_ADD_LVALUE_REFERENCE,
	TYPE_TRANSFORM_ADD_POINTER,
	TYPE_TRANSFORM_ADD_RVALUE_REFERENCE,
	TYPE_TRANSFORM_DECAY,
	TYPE_TRANSFORM_MAKE_SIGNED,
	TYPE_TRANSFORM_MAKE_UNSIGNED,
	TYPE_TRANSFORM_REMOVE_ALL_EXTENTS,
	TYPE_TRANSFORM_REMOVE_CONST,
	TYPE_TRANSFORM_REMOVE_CV,
	TYPE_TRANSFORM_REMOVE_CVREF,
	TYPE_TRANSFORM_REMOVE_POINTER,
	TYPE_TRANSFORM_REMOVE_REFERENCE,
	TYPE_TRANSFORM_REMOVE_VOLATILE,
	TYPE_TRANSFORM_UNDERLYING_TYPE
};

enum IntegerIntrinsicKind : std::uint8_t
{
	INTEGER_INTRINSIC_NONE,
	INTEGER_INTRINSIC_BSWAP16,
	INTEGER_INTRINSIC_BSWAP32,
	INTEGER_INTRINSIC_BSWAP64,
	INTEGER_INTRINSIC_CLZ,
	INTEGER_INTRINSIC_CLZG,
	INTEGER_INTRINSIC_CLZL,
	INTEGER_INTRINSIC_CLZLL,
	INTEGER_INTRINSIC_CTZ,
	INTEGER_INTRINSIC_CTZG,
	INTEGER_INTRINSIC_CTZL,
	INTEGER_INTRINSIC_CTZLL,
	INTEGER_INTRINSIC_POPCOUNT,
	INTEGER_INTRINSIC_POPCOUNTG,
	INTEGER_INTRINSIC_POPCOUNTL,
	INTEGER_INTRINSIC_POPCOUNTLL,
	INTEGER_INTRINSIC_COUNT
};

enum IntegerIntrinsicOperation
{
	INTEGER_OPERATION_BSWAP,
	INTEGER_OPERATION_CLZ,
	INTEGER_OPERATION_CTZ,
	INTEGER_OPERATION_POPCOUNT
};

enum IntegerIntrinsicArgumentRule
{
	INTEGER_ARGUMENT_UNSIGNED_SHORT,
	INTEGER_ARGUMENT_UNSIGNED_INT,
	INTEGER_ARGUMENT_UNSIGNED_LONG,
	INTEGER_ARGUMENT_UNSIGNED_LONG_LONG,
	INTEGER_ARGUMENT_GENERIC_UNSIGNED
};

struct IntegerIntrinsic
{
	const char* spelling;
	IntegerIntrinsicKind kind;
	IntegerIntrinsicOperation operation;
	IntegerIntrinsicArgumentRule argument_rule;
	unsigned arity;
};

enum FloatingIntrinsicKind : std::uint8_t
{
	FLOATING_INTRINSIC_NONE,
	FLOATING_INTRINSIC_ACOS,
	FLOATING_INTRINSIC_ACOSF,
	FLOATING_INTRINSIC_ACOSH,
	FLOATING_INTRINSIC_ACOSHF,
	FLOATING_INTRINSIC_ACOSHL,
	FLOATING_INTRINSIC_ACOSL,
	FLOATING_INTRINSIC_ASIN,
	FLOATING_INTRINSIC_ASINF,
	FLOATING_INTRINSIC_ASINH,
	FLOATING_INTRINSIC_ASINHF,
	FLOATING_INTRINSIC_ASINHL,
	FLOATING_INTRINSIC_ASINL,
	FLOATING_INTRINSIC_ATAN,
	FLOATING_INTRINSIC_ATAN2,
	FLOATING_INTRINSIC_ATAN2F,
	FLOATING_INTRINSIC_ATAN2L,
	FLOATING_INTRINSIC_ATANF,
	FLOATING_INTRINSIC_ATANH,
	FLOATING_INTRINSIC_ATANHF,
	FLOATING_INTRINSIC_ATANHL,
	FLOATING_INTRINSIC_ATANL,
	FLOATING_INTRINSIC_CBRT,
	FLOATING_INTRINSIC_CBRTF,
	FLOATING_INTRINSIC_CBRTL,
	FLOATING_INTRINSIC_CEIL,
	FLOATING_INTRINSIC_CEILF,
	FLOATING_INTRINSIC_CEILL,
	FLOATING_INTRINSIC_COPYSIGN,
	FLOATING_INTRINSIC_COPYSIGNF,
	FLOATING_INTRINSIC_COPYSIGNL,
	FLOATING_INTRINSIC_COS,
	FLOATING_INTRINSIC_COSF,
	FLOATING_INTRINSIC_COSH,
	FLOATING_INTRINSIC_COSHF,
	FLOATING_INTRINSIC_COSHL,
	FLOATING_INTRINSIC_COSL,
	FLOATING_INTRINSIC_ERF,
	FLOATING_INTRINSIC_ERFC,
	FLOATING_INTRINSIC_ERFCF,
	FLOATING_INTRINSIC_ERFCL,
	FLOATING_INTRINSIC_ERFF,
	FLOATING_INTRINSIC_ERFL,
	FLOATING_INTRINSIC_EXP,
	FLOATING_INTRINSIC_EXP2,
	FLOATING_INTRINSIC_EXP2F,
	FLOATING_INTRINSIC_EXP2L,
	FLOATING_INTRINSIC_EXPF,
	FLOATING_INTRINSIC_EXPL,
	FLOATING_INTRINSIC_EXPM1,
	FLOATING_INTRINSIC_EXPM1F,
	FLOATING_INTRINSIC_EXPM1L,
	FLOATING_INTRINSIC_FABS,
	FLOATING_INTRINSIC_FABSF,
	FLOATING_INTRINSIC_FABSL,
	FLOATING_INTRINSIC_FDIM,
	FLOATING_INTRINSIC_FDIMF,
	FLOATING_INTRINSIC_FDIML,
	FLOATING_INTRINSIC_FLOOR,
	FLOATING_INTRINSIC_FLOORF,
	FLOATING_INTRINSIC_FLOORL,
	FLOATING_INTRINSIC_FLT_ROUNDS,
	FLOATING_INTRINSIC_FMA,
	FLOATING_INTRINSIC_FMAF,
	FLOATING_INTRINSIC_FMAL,
	FLOATING_INTRINSIC_FMAX,
	FLOATING_INTRINSIC_FMAXF,
	FLOATING_INTRINSIC_FMAXL,
	FLOATING_INTRINSIC_FMIN,
	FLOATING_INTRINSIC_FMINF,
	FLOATING_INTRINSIC_FMINL,
	FLOATING_INTRINSIC_FMOD,
	FLOATING_INTRINSIC_FMODF,
	FLOATING_INTRINSIC_FMODL,
	FLOATING_INTRINSIC_FPCLASSIFY,
	FLOATING_INTRINSIC_FREXP,
	FLOATING_INTRINSIC_FREXPF,
	FLOATING_INTRINSIC_FREXPL,
	FLOATING_INTRINSIC_HUGE_VAL,
	FLOATING_INTRINSIC_HUGE_VALF,
	FLOATING_INTRINSIC_HUGE_VALL,
	FLOATING_INTRINSIC_HYPOT,
	FLOATING_INTRINSIC_HYPOTF,
	FLOATING_INTRINSIC_HYPOTL,
	FLOATING_INTRINSIC_ILOGB,
	FLOATING_INTRINSIC_ILOGBF,
	FLOATING_INTRINSIC_ILOGBL,
	FLOATING_INTRINSIC_INF,
	FLOATING_INTRINSIC_INFF,
	FLOATING_INTRINSIC_INFL,
	FLOATING_INTRINSIC_ISFINITE,
	FLOATING_INTRINSIC_ISINF,
	FLOATING_INTRINSIC_ISNAN,
	FLOATING_INTRINSIC_ISNORMAL,
	FLOATING_INTRINSIC_LDEXP,
	FLOATING_INTRINSIC_LDEXPF,
	FLOATING_INTRINSIC_LDEXPL,
	FLOATING_INTRINSIC_LGAMMA,
	FLOATING_INTRINSIC_LGAMMAF,
	FLOATING_INTRINSIC_LGAMMAL,
	FLOATING_INTRINSIC_LLRINT,
	FLOATING_INTRINSIC_LLRINTF,
	FLOATING_INTRINSIC_LLRINTL,
	FLOATING_INTRINSIC_LLROUND,
	FLOATING_INTRINSIC_LLROUNDF,
	FLOATING_INTRINSIC_LLROUNDL,
	FLOATING_INTRINSIC_LOG,
	FLOATING_INTRINSIC_LOG10,
	FLOATING_INTRINSIC_LOG10F,
	FLOATING_INTRINSIC_LOG10L,
	FLOATING_INTRINSIC_LOG1P,
	FLOATING_INTRINSIC_LOG1PF,
	FLOATING_INTRINSIC_LOG1PL,
	FLOATING_INTRINSIC_LOG2,
	FLOATING_INTRINSIC_LOG2F,
	FLOATING_INTRINSIC_LOG2L,
	FLOATING_INTRINSIC_LOGB,
	FLOATING_INTRINSIC_LOGBF,
	FLOATING_INTRINSIC_LOGBL,
	FLOATING_INTRINSIC_LOGF,
	FLOATING_INTRINSIC_LOGL,
	FLOATING_INTRINSIC_LRINT,
	FLOATING_INTRINSIC_LRINTF,
	FLOATING_INTRINSIC_LRINTL,
	FLOATING_INTRINSIC_LROUND,
	FLOATING_INTRINSIC_LROUNDF,
	FLOATING_INTRINSIC_LROUNDL,
	FLOATING_INTRINSIC_MODF,
	FLOATING_INTRINSIC_MODFF,
	FLOATING_INTRINSIC_MODFL,
	FLOATING_INTRINSIC_NAN,
	FLOATING_INTRINSIC_NANF,
	FLOATING_INTRINSIC_NANL,
	FLOATING_INTRINSIC_NANS,
	FLOATING_INTRINSIC_NANSF,
	FLOATING_INTRINSIC_NANSL,
	FLOATING_INTRINSIC_NEARBYINT,
	FLOATING_INTRINSIC_NEARBYINTF,
	FLOATING_INTRINSIC_NEARBYINTL,
	FLOATING_INTRINSIC_NEXTAFTER,
	FLOATING_INTRINSIC_NEXTAFTERF,
	FLOATING_INTRINSIC_NEXTAFTERL,
	FLOATING_INTRINSIC_NEXTTOWARD,
	FLOATING_INTRINSIC_NEXTTOWARDF,
	FLOATING_INTRINSIC_NEXTTOWARDL,
	FLOATING_INTRINSIC_POW,
	FLOATING_INTRINSIC_POWF,
	FLOATING_INTRINSIC_POWL,
	FLOATING_INTRINSIC_REMAINDER,
	FLOATING_INTRINSIC_REMAINDERF,
	FLOATING_INTRINSIC_REMAINDERL,
	FLOATING_INTRINSIC_REMQUO,
	FLOATING_INTRINSIC_REMQUOF,
	FLOATING_INTRINSIC_REMQUOL,
	FLOATING_INTRINSIC_RINT,
	FLOATING_INTRINSIC_RINTF,
	FLOATING_INTRINSIC_RINTL,
	FLOATING_INTRINSIC_ROUND,
	FLOATING_INTRINSIC_ROUNDF,
	FLOATING_INTRINSIC_ROUNDL,
	FLOATING_INTRINSIC_SCALBLN,
	FLOATING_INTRINSIC_SCALBLNF,
	FLOATING_INTRINSIC_SCALBLNL,
	FLOATING_INTRINSIC_SCALBN,
	FLOATING_INTRINSIC_SCALBNF,
	FLOATING_INTRINSIC_SCALBNL,
	FLOATING_INTRINSIC_SIGNBIT,
	FLOATING_INTRINSIC_SIN,
	FLOATING_INTRINSIC_SINF,
	FLOATING_INTRINSIC_SINH,
	FLOATING_INTRINSIC_SINHF,
	FLOATING_INTRINSIC_SINHL,
	FLOATING_INTRINSIC_SINL,
	FLOATING_INTRINSIC_SQRT,
	FLOATING_INTRINSIC_SQRTF,
	FLOATING_INTRINSIC_SQRTL,
	FLOATING_INTRINSIC_TAN,
	FLOATING_INTRINSIC_TANF,
	FLOATING_INTRINSIC_TANH,
	FLOATING_INTRINSIC_TANHF,
	FLOATING_INTRINSIC_TANHL,
	FLOATING_INTRINSIC_TANL,
	FLOATING_INTRINSIC_TGAMMA,
	FLOATING_INTRINSIC_TGAMMAF,
	FLOATING_INTRINSIC_TGAMMAL,
	FLOATING_INTRINSIC_TRUNC,
	FLOATING_INTRINSIC_TRUNCF,
	FLOATING_INTRINSIC_TRUNCL,
	FLOATING_INTRINSIC_COUNT
};

enum FloatingIntrinsicOperation
{
	FLOATING_OPERATION_EXTERNAL_LIBM,
	// The libm entries whose operands are not all the floating type.  The
	// format still names that type; these name the rest of the signature.
	FLOATING_OPERATION_EXTERNAL_LIBM_EXPONENT_OUT,
	FLOATING_OPERATION_EXTERNAL_LIBM_EXPONENT_IN,
	FLOATING_OPERATION_EXTERNAL_LIBM_LONG_EXPONENT_IN,
	FLOATING_OPERATION_EXTERNAL_LIBM_PART_OUT,
	FLOATING_OPERATION_EXTERNAL_LIBM_QUOTIENT_OUT,
	FLOATING_OPERATION_EXTERNAL_LIBM_WIDE_SECOND,
	FLOATING_OPERATION_EXTERNAL_LIBM_TO_INT,
	FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG,
	FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG_LONG,
	FLOATING_OPERATION_ROUNDING_MODE,
	FLOATING_OPERATION_CLASSIFY,
	FLOATING_OPERATION_INFINITY,
	FLOATING_OPERATION_ISFINITE,
	FLOATING_OPERATION_ISINF,
	FLOATING_OPERATION_ISNAN,
	FLOATING_OPERATION_ISNORMAL,
	FLOATING_OPERATION_NAN,
	FLOATING_OPERATION_SNAN,
	FLOATING_OPERATION_SIGNBIT
};

// Every one of these lowers to a call to the C library function of the same
// name; they differ only in the signature they declare for it.  Both the
// semantic side and the lowering have to agree on the whole set, so ask here
// rather than naming the members twice.
inline bool IsExternalLibmOperation(FloatingIntrinsicOperation operation)
{
	return operation >= FLOATING_OPERATION_EXTERNAL_LIBM &&
		operation <= FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG_LONG;
}

enum FloatingIntrinsicFormat
{
	FLOATING_FORMAT_NONE,
	FLOATING_FORMAT_FLOAT,
	FLOATING_FORMAT_DOUBLE,
	FLOATING_FORMAT_LONG_DOUBLE
};

struct FloatingIntrinsic
{
	const char* spelling;
	FloatingIntrinsicKind kind;
	FloatingIntrinsicOperation operation;
	FloatingIntrinsicFormat result_format;
	unsigned arity;
};

enum MemoryIntrinsicKind : std::uint8_t
{
	MEMORY_INTRINSIC_NONE,
	MEMORY_INTRINSIC_ASSUME_ALIGNED,
	MEMORY_INTRINSIC_BZERO,
	MEMORY_INTRINSIC_MEMCHR,
	MEMORY_INTRINSIC_MEMCMP,
	MEMORY_INTRINSIC_MEMCPY,
	MEMORY_INTRINSIC_MEMMOVE,
	MEMORY_INTRINSIC_MEMSET,
	MEMORY_INTRINSIC_PREFETCH,
	MEMORY_INTRINSIC_STRCHR,
	MEMORY_INTRINSIC_STRCMP,
	MEMORY_INTRINSIC_STRLEN,
	MEMORY_INTRINSIC_COUNT
};

enum MemoryIntrinsicEffect
{
	MEMORY_EFFECT_READNONE,
	MEMORY_EFFECT_READONLY,
	MEMORY_EFFECT_READWRITE
};

enum MemoryIntrinsicLowering
{
	MEMORY_LOWER_IDENTITY,
	MEMORY_LOWER_NOOP,
	MEMORY_LOWER_EXTERNAL
};

struct MemoryIntrinsic
{
	const char* spelling;
	MemoryIntrinsicKind kind;
	unsigned minimum_arity;
	unsigned maximum_arity;
	MemoryIntrinsicEffect effect;
	MemoryIntrinsicLowering lowering;
};

enum VectorIntrinsicKind : std::uint8_t
{
	VECTOR_INTRINSIC_NONE,
	VECTOR_INTRINSIC_IA32_VEC_EXT_V2SI,
	VECTOR_INTRINSIC_IA32_VEC_INIT_V2SI,
	VECTOR_INTRINSIC_IA32_VEC_INIT_V4HI,
	VECTOR_INTRINSIC_IA32_VEC_INIT_V8QI,
	VECTOR_INTRINSIC_COUNT
};

enum VectorIntrinsicOperation
{
	VECTOR_OPERATION_INIT,
	VECTOR_OPERATION_EXTRACT
};

enum VectorIntrinsicElement
{
	VECTOR_ELEMENT_I8,
	VECTOR_ELEMENT_I16,
	VECTOR_ELEMENT_I32
};

struct VectorIntrinsic
{
	const char* spelling;
	VectorIntrinsicKind kind;
	VectorIntrinsicOperation operation;
	VectorIntrinsicElement element;
	unsigned lane_count;
};

enum AtomicIntrinsicKind : std::uint8_t
{
	ATOMIC_INTRINSIC_NONE,
	ATOMIC_INTRINSIC_ADD_FETCH,
	ATOMIC_INTRINSIC_ALWAYS_LOCK_FREE,
	ATOMIC_INTRINSIC_CLEAR,
	ATOMIC_INTRINSIC_COMPARE_EXCHANGE_N,
	ATOMIC_INTRINSIC_EXCHANGE_N,
	ATOMIC_INTRINSIC_FETCH_ADD,
	ATOMIC_INTRINSIC_FETCH_AND,
	ATOMIC_INTRINSIC_FETCH_OR,
	ATOMIC_INTRINSIC_FETCH_SUB,
	ATOMIC_INTRINSIC_FETCH_XOR,
	ATOMIC_INTRINSIC_IS_LOCK_FREE,
	ATOMIC_INTRINSIC_LOAD,
	ATOMIC_INTRINSIC_LOAD_N,
	ATOMIC_INTRINSIC_SIGNAL_FENCE,
	ATOMIC_INTRINSIC_STORE,
	ATOMIC_INTRINSIC_STORE_N,
	ATOMIC_INTRINSIC_TEST_AND_SET,
	ATOMIC_INTRINSIC_THREAD_FENCE,
	ATOMIC_INTRINSIC_C11_COMPARE_EXCHANGE_STRONG,
	ATOMIC_INTRINSIC_C11_COMPARE_EXCHANGE_WEAK,
	ATOMIC_INTRINSIC_C11_EXCHANGE,
	ATOMIC_INTRINSIC_C11_FETCH_ADD,
	ATOMIC_INTRINSIC_C11_FETCH_AND,
	ATOMIC_INTRINSIC_C11_FETCH_OR,
	ATOMIC_INTRINSIC_C11_FETCH_SUB,
	ATOMIC_INTRINSIC_C11_FETCH_XOR,
	ATOMIC_INTRINSIC_C11_INIT,
	ATOMIC_INTRINSIC_C11_IS_LOCK_FREE,
	ATOMIC_INTRINSIC_C11_LOAD,
	ATOMIC_INTRINSIC_C11_SIGNAL_FENCE,
	ATOMIC_INTRINSIC_C11_STORE,
	ATOMIC_INTRINSIC_C11_THREAD_FENCE,
	ATOMIC_INTRINSIC_SYNC_FETCH_AND_ADD,
	ATOMIC_INTRINSIC_SYNC_LOCK_RELEASE,
	ATOMIC_INTRINSIC_SYNC_LOCK_TEST_AND_SET,
	ATOMIC_INTRINSIC_SYNC_SYNCHRONIZE,
	ATOMIC_INTRINSIC_SYNC_VAL_COMPARE_AND_SWAP,
	ATOMIC_INTRINSIC_COUNT
};

enum AtomicIntrinsicShape
{
	ATOMIC_SHAPE_LOCK_FREE,
	ATOMIC_SHAPE_LOAD,
	ATOMIC_SHAPE_LOAD_OUT,
	ATOMIC_SHAPE_STORE,
	ATOMIC_SHAPE_STORE_FROM,
	ATOMIC_SHAPE_EXCHANGE,
	ATOMIC_SHAPE_COMPARE_EXCHANGE,
	ATOMIC_SHAPE_SYNC_COMPARE_EXCHANGE,
	ATOMIC_SHAPE_FETCH_UPDATE,
	ATOMIC_SHAPE_TEST_AND_SET,
	ATOMIC_SHAPE_CLEAR,
	ATOMIC_SHAPE_FENCE
};

enum AtomicUpdateOperation
{
	ATOMIC_UPDATE_NONE,
	ATOMIC_UPDATE_ADD,
	ATOMIC_UPDATE_SUB,
	ATOMIC_UPDATE_AND,
	ATOMIC_UPDATE_OR,
	ATOMIC_UPDATE_XOR
};

struct AtomicIntrinsic
{
	const char* spelling;
	AtomicIntrinsicKind kind;
	AtomicIntrinsicShape shape;
	AtomicUpdateOperation update;
	unsigned arity;
	bool result_is_new;
	bool requires_atomic_pointee;
};

TypeTraitKind FindTypeTrait(const std::string& spelling);
TypeTransformKind FindTypeTransform(const std::string& spelling);
const IntegerIntrinsic* FindIntegerIntrinsic(const std::string& spelling);
const IntegerIntrinsic& GetIntegerIntrinsic(IntegerIntrinsicKind kind);
const FloatingIntrinsic* FindFloatingIntrinsic(const std::string& spelling);
const FloatingIntrinsic& GetFloatingIntrinsic(FloatingIntrinsicKind kind);
const MemoryIntrinsic* FindMemoryIntrinsic(const std::string& spelling);
const MemoryIntrinsic& GetMemoryIntrinsic(MemoryIntrinsicKind kind);
const VectorIntrinsic* FindVectorIntrinsic(const std::string& spelling);
const VectorIntrinsic& GetVectorIntrinsic(VectorIntrinsicKind kind);
const AtomicIntrinsic* FindAtomicIntrinsic(const std::string& spelling);
const AtomicIntrinsic& GetAtomicIntrinsic(AtomicIntrinsicKind kind);

}
}
