#include "preprocess/hosted/builtin_registry.h"
#include "support/exceptions.h"

#include <cstddef>
#include <stdexcept>

namespace cppgm
{
namespace hosted_builtin
{
namespace
{

const IntegerIntrinsic kIntegerIntrinsics[] = {
	{"__builtin_bswap16", INTEGER_INTRINSIC_BSWAP16,
		INTEGER_OPERATION_BSWAP, INTEGER_ARGUMENT_UNSIGNED_SHORT, 1},
	{"__builtin_bswap32", INTEGER_INTRINSIC_BSWAP32,
		INTEGER_OPERATION_BSWAP, INTEGER_ARGUMENT_UNSIGNED_INT, 1},
	{"__builtin_bswap64", INTEGER_INTRINSIC_BSWAP64,
		INTEGER_OPERATION_BSWAP, INTEGER_ARGUMENT_UNSIGNED_LONG_LONG, 1},
	{"__builtin_clz", INTEGER_INTRINSIC_CLZ,
		INTEGER_OPERATION_CLZ, INTEGER_ARGUMENT_UNSIGNED_INT, 1},
	{"__builtin_clzg", INTEGER_INTRINSIC_CLZG,
		INTEGER_OPERATION_CLZ, INTEGER_ARGUMENT_GENERIC_UNSIGNED, 2},
	{"__builtin_clzl", INTEGER_INTRINSIC_CLZL,
		INTEGER_OPERATION_CLZ, INTEGER_ARGUMENT_UNSIGNED_LONG, 1},
	{"__builtin_clzll", INTEGER_INTRINSIC_CLZLL,
		INTEGER_OPERATION_CLZ, INTEGER_ARGUMENT_UNSIGNED_LONG_LONG, 1},
	{"__builtin_ctz", INTEGER_INTRINSIC_CTZ,
		INTEGER_OPERATION_CTZ, INTEGER_ARGUMENT_UNSIGNED_INT, 1},
	{"__builtin_ctzg", INTEGER_INTRINSIC_CTZG,
		INTEGER_OPERATION_CTZ, INTEGER_ARGUMENT_GENERIC_UNSIGNED, 2},
	{"__builtin_ctzl", INTEGER_INTRINSIC_CTZL,
		INTEGER_OPERATION_CTZ, INTEGER_ARGUMENT_UNSIGNED_LONG, 1},
	{"__builtin_ctzll", INTEGER_INTRINSIC_CTZLL,
		INTEGER_OPERATION_CTZ, INTEGER_ARGUMENT_UNSIGNED_LONG_LONG, 1},
	{"__builtin_popcount", INTEGER_INTRINSIC_POPCOUNT,
		INTEGER_OPERATION_POPCOUNT, INTEGER_ARGUMENT_UNSIGNED_INT, 1},
	{"__builtin_popcountg", INTEGER_INTRINSIC_POPCOUNTG,
		INTEGER_OPERATION_POPCOUNT, INTEGER_ARGUMENT_GENERIC_UNSIGNED, 1},
	{"__builtin_popcountl", INTEGER_INTRINSIC_POPCOUNTL,
		INTEGER_OPERATION_POPCOUNT, INTEGER_ARGUMENT_UNSIGNED_LONG, 1},
	{"__builtin_popcountll", INTEGER_INTRINSIC_POPCOUNTLL,
		INTEGER_OPERATION_POPCOUNT, INTEGER_ARGUMENT_UNSIGNED_LONG_LONG, 1}
};

const FloatingIntrinsic kFloatingIntrinsics[] = {
	{"__builtin_acos", FLOATING_INTRINSIC_ACOS,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_acosf", FLOATING_INTRINSIC_ACOSF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_acosh", FLOATING_INTRINSIC_ACOSH,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_acoshf", FLOATING_INTRINSIC_ACOSHF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_acoshl", FLOATING_INTRINSIC_ACOSHL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_acosl", FLOATING_INTRINSIC_ACOSL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_asin", FLOATING_INTRINSIC_ASIN,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_asinf", FLOATING_INTRINSIC_ASINF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_asinh", FLOATING_INTRINSIC_ASINH,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_asinhf", FLOATING_INTRINSIC_ASINHF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_asinhl", FLOATING_INTRINSIC_ASINHL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_asinl", FLOATING_INTRINSIC_ASINL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_atan", FLOATING_INTRINSIC_ATAN,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_atan2", FLOATING_INTRINSIC_ATAN2,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_atan2f", FLOATING_INTRINSIC_ATAN2F,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_atan2l", FLOATING_INTRINSIC_ATAN2L,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_atanf", FLOATING_INTRINSIC_ATANF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_atanh", FLOATING_INTRINSIC_ATANH,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_atanhf", FLOATING_INTRINSIC_ATANHF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_atanhl", FLOATING_INTRINSIC_ATANHL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_atanl", FLOATING_INTRINSIC_ATANL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_cbrt", FLOATING_INTRINSIC_CBRT,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_cbrtf", FLOATING_INTRINSIC_CBRTF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_cbrtl", FLOATING_INTRINSIC_CBRTL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_ceil", FLOATING_INTRINSIC_CEIL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_ceilf", FLOATING_INTRINSIC_CEILF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_ceill", FLOATING_INTRINSIC_CEILL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_copysign", FLOATING_INTRINSIC_COPYSIGN,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_copysignf", FLOATING_INTRINSIC_COPYSIGNF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_copysignl", FLOATING_INTRINSIC_COPYSIGNL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_cos", FLOATING_INTRINSIC_COS,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_cosf", FLOATING_INTRINSIC_COSF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_cosh", FLOATING_INTRINSIC_COSH,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_coshf", FLOATING_INTRINSIC_COSHF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_coshl", FLOATING_INTRINSIC_COSHL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_cosl", FLOATING_INTRINSIC_COSL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_erf", FLOATING_INTRINSIC_ERF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_erfc", FLOATING_INTRINSIC_ERFC,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_erfcf", FLOATING_INTRINSIC_ERFCF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_erfcl", FLOATING_INTRINSIC_ERFCL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_erff", FLOATING_INTRINSIC_ERFF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_erfl", FLOATING_INTRINSIC_ERFL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_exp", FLOATING_INTRINSIC_EXP,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_exp2", FLOATING_INTRINSIC_EXP2,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_exp2f", FLOATING_INTRINSIC_EXP2F,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_exp2l", FLOATING_INTRINSIC_EXP2L,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_expf", FLOATING_INTRINSIC_EXPF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_expl", FLOATING_INTRINSIC_EXPL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_expm1", FLOATING_INTRINSIC_EXPM1,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_expm1f", FLOATING_INTRINSIC_EXPM1F,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_expm1l", FLOATING_INTRINSIC_EXPM1L,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_fabs", FLOATING_INTRINSIC_FABS,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_fabsf", FLOATING_INTRINSIC_FABSF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_fabsl", FLOATING_INTRINSIC_FABSL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_fdim", FLOATING_INTRINSIC_FDIM,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_fdimf", FLOATING_INTRINSIC_FDIMF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_fdiml", FLOATING_INTRINSIC_FDIML,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_floor", FLOATING_INTRINSIC_FLOOR,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_floorf", FLOATING_INTRINSIC_FLOORF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_floorl", FLOATING_INTRINSIC_FLOORL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_flt_rounds", FLOATING_INTRINSIC_FLT_ROUNDS,
		FLOATING_OPERATION_ROUNDING_MODE, FLOATING_FORMAT_NONE, 0},
	{"__builtin_fma", FLOATING_INTRINSIC_FMA,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 3},
	{"__builtin_fmaf", FLOATING_INTRINSIC_FMAF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 3},
	{"__builtin_fmal", FLOATING_INTRINSIC_FMAL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 3},
	{"__builtin_fmax", FLOATING_INTRINSIC_FMAX,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_fmaxf", FLOATING_INTRINSIC_FMAXF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_fmaxl", FLOATING_INTRINSIC_FMAXL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_fmin", FLOATING_INTRINSIC_FMIN,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_fminf", FLOATING_INTRINSIC_FMINF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_fminl", FLOATING_INTRINSIC_FMINL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_fmod", FLOATING_INTRINSIC_FMOD,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_fmodf", FLOATING_INTRINSIC_FMODF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_fmodl", FLOATING_INTRINSIC_FMODL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_fpclassify", FLOATING_INTRINSIC_FPCLASSIFY,
		FLOATING_OPERATION_CLASSIFY, FLOATING_FORMAT_NONE, 6},
	{"__builtin_frexp", FLOATING_INTRINSIC_FREXP,
		FLOATING_OPERATION_EXTERNAL_LIBM_EXPONENT_OUT, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_frexpf", FLOATING_INTRINSIC_FREXPF,
		FLOATING_OPERATION_EXTERNAL_LIBM_EXPONENT_OUT, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_frexpl", FLOATING_INTRINSIC_FREXPL,
		FLOATING_OPERATION_EXTERNAL_LIBM_EXPONENT_OUT, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_huge_val", FLOATING_INTRINSIC_HUGE_VAL,
		FLOATING_OPERATION_INFINITY, FLOATING_FORMAT_DOUBLE, 0},
	{"__builtin_huge_valf", FLOATING_INTRINSIC_HUGE_VALF,
		FLOATING_OPERATION_INFINITY, FLOATING_FORMAT_FLOAT, 0},
	{"__builtin_huge_vall", FLOATING_INTRINSIC_HUGE_VALL,
		FLOATING_OPERATION_INFINITY, FLOATING_FORMAT_LONG_DOUBLE, 0},
	{"__builtin_hypot", FLOATING_INTRINSIC_HYPOT,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_hypotf", FLOATING_INTRINSIC_HYPOTF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_hypotl", FLOATING_INTRINSIC_HYPOTL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_ilogb", FLOATING_INTRINSIC_ILOGB,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_INT, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_ilogbf", FLOATING_INTRINSIC_ILOGBF,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_INT, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_ilogbl", FLOATING_INTRINSIC_ILOGBL,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_INT, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_inf", FLOATING_INTRINSIC_INF,
		FLOATING_OPERATION_INFINITY, FLOATING_FORMAT_DOUBLE, 0},
	{"__builtin_inff", FLOATING_INTRINSIC_INFF,
		FLOATING_OPERATION_INFINITY, FLOATING_FORMAT_FLOAT, 0},
	{"__builtin_infl", FLOATING_INTRINSIC_INFL,
		FLOATING_OPERATION_INFINITY, FLOATING_FORMAT_LONG_DOUBLE, 0},
	{"__builtin_isfinite", FLOATING_INTRINSIC_ISFINITE,
		FLOATING_OPERATION_ISFINITE, FLOATING_FORMAT_NONE, 1},
	{"__builtin_isinf", FLOATING_INTRINSIC_ISINF,
		FLOATING_OPERATION_ISINF, FLOATING_FORMAT_NONE, 1},
	{"__builtin_isnan", FLOATING_INTRINSIC_ISNAN,
		FLOATING_OPERATION_ISNAN, FLOATING_FORMAT_NONE, 1},
	{"__builtin_isnormal", FLOATING_INTRINSIC_ISNORMAL,
		FLOATING_OPERATION_ISNORMAL, FLOATING_FORMAT_NONE, 1},
	{"__builtin_ldexp", FLOATING_INTRINSIC_LDEXP,
		FLOATING_OPERATION_EXTERNAL_LIBM_EXPONENT_IN, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_ldexpf", FLOATING_INTRINSIC_LDEXPF,
		FLOATING_OPERATION_EXTERNAL_LIBM_EXPONENT_IN, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_ldexpl", FLOATING_INTRINSIC_LDEXPL,
		FLOATING_OPERATION_EXTERNAL_LIBM_EXPONENT_IN, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_lgamma", FLOATING_INTRINSIC_LGAMMA,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_lgammaf", FLOATING_INTRINSIC_LGAMMAF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_lgammal", FLOATING_INTRINSIC_LGAMMAL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_llrint", FLOATING_INTRINSIC_LLRINT,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG_LONG, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_llrintf", FLOATING_INTRINSIC_LLRINTF,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG_LONG, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_llrintl", FLOATING_INTRINSIC_LLRINTL,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG_LONG, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_llround", FLOATING_INTRINSIC_LLROUND,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG_LONG, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_llroundf", FLOATING_INTRINSIC_LLROUNDF,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG_LONG, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_llroundl", FLOATING_INTRINSIC_LLROUNDL,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG_LONG, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_log", FLOATING_INTRINSIC_LOG,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_log10", FLOATING_INTRINSIC_LOG10,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_log10f", FLOATING_INTRINSIC_LOG10F,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_log10l", FLOATING_INTRINSIC_LOG10L,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_log1p", FLOATING_INTRINSIC_LOG1P,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_log1pf", FLOATING_INTRINSIC_LOG1PF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_log1pl", FLOATING_INTRINSIC_LOG1PL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_log2", FLOATING_INTRINSIC_LOG2,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_log2f", FLOATING_INTRINSIC_LOG2F,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_log2l", FLOATING_INTRINSIC_LOG2L,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_logb", FLOATING_INTRINSIC_LOGB,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_logbf", FLOATING_INTRINSIC_LOGBF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_logbl", FLOATING_INTRINSIC_LOGBL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_logf", FLOATING_INTRINSIC_LOGF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_logl", FLOATING_INTRINSIC_LOGL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_lrint", FLOATING_INTRINSIC_LRINT,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_lrintf", FLOATING_INTRINSIC_LRINTF,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_lrintl", FLOATING_INTRINSIC_LRINTL,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_lround", FLOATING_INTRINSIC_LROUND,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_lroundf", FLOATING_INTRINSIC_LROUNDF,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_lroundl", FLOATING_INTRINSIC_LROUNDL,
		FLOATING_OPERATION_EXTERNAL_LIBM_TO_LONG, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_modf", FLOATING_INTRINSIC_MODF,
		FLOATING_OPERATION_EXTERNAL_LIBM_PART_OUT, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_modff", FLOATING_INTRINSIC_MODFF,
		FLOATING_OPERATION_EXTERNAL_LIBM_PART_OUT, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_modfl", FLOATING_INTRINSIC_MODFL,
		FLOATING_OPERATION_EXTERNAL_LIBM_PART_OUT, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_nan", FLOATING_INTRINSIC_NAN,
		FLOATING_OPERATION_NAN, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_nanf", FLOATING_INTRINSIC_NANF,
		FLOATING_OPERATION_NAN, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_nanl", FLOATING_INTRINSIC_NANL,
		FLOATING_OPERATION_NAN, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_nans", FLOATING_INTRINSIC_NANS,
		FLOATING_OPERATION_SNAN, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_nansf", FLOATING_INTRINSIC_NANSF,
		FLOATING_OPERATION_SNAN, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_nansl", FLOATING_INTRINSIC_NANSL,
		FLOATING_OPERATION_SNAN, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_nearbyint", FLOATING_INTRINSIC_NEARBYINT,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_nearbyintf", FLOATING_INTRINSIC_NEARBYINTF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_nearbyintl", FLOATING_INTRINSIC_NEARBYINTL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_nextafter", FLOATING_INTRINSIC_NEXTAFTER,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_nextafterf", FLOATING_INTRINSIC_NEXTAFTERF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_nextafterl", FLOATING_INTRINSIC_NEXTAFTERL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_nexttoward", FLOATING_INTRINSIC_NEXTTOWARD,
		FLOATING_OPERATION_EXTERNAL_LIBM_WIDE_SECOND, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_nexttowardf", FLOATING_INTRINSIC_NEXTTOWARDF,
		FLOATING_OPERATION_EXTERNAL_LIBM_WIDE_SECOND, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_nexttowardl", FLOATING_INTRINSIC_NEXTTOWARDL,
		FLOATING_OPERATION_EXTERNAL_LIBM_WIDE_SECOND, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_pow", FLOATING_INTRINSIC_POW,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_powf", FLOATING_INTRINSIC_POWF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_powl", FLOATING_INTRINSIC_POWL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_remainder", FLOATING_INTRINSIC_REMAINDER,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_remainderf", FLOATING_INTRINSIC_REMAINDERF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_remainderl", FLOATING_INTRINSIC_REMAINDERL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_remquo", FLOATING_INTRINSIC_REMQUO,
		FLOATING_OPERATION_EXTERNAL_LIBM_QUOTIENT_OUT, FLOATING_FORMAT_DOUBLE, 3},
	{"__builtin_remquof", FLOATING_INTRINSIC_REMQUOF,
		FLOATING_OPERATION_EXTERNAL_LIBM_QUOTIENT_OUT, FLOATING_FORMAT_FLOAT, 3},
	{"__builtin_remquol", FLOATING_INTRINSIC_REMQUOL,
		FLOATING_OPERATION_EXTERNAL_LIBM_QUOTIENT_OUT, FLOATING_FORMAT_LONG_DOUBLE, 3},
	{"__builtin_rint", FLOATING_INTRINSIC_RINT,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_rintf", FLOATING_INTRINSIC_RINTF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_rintl", FLOATING_INTRINSIC_RINTL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_round", FLOATING_INTRINSIC_ROUND,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_roundf", FLOATING_INTRINSIC_ROUNDF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_roundl", FLOATING_INTRINSIC_ROUNDL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_scalbln", FLOATING_INTRINSIC_SCALBLN,
		FLOATING_OPERATION_EXTERNAL_LIBM_LONG_EXPONENT_IN, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_scalblnf", FLOATING_INTRINSIC_SCALBLNF,
		FLOATING_OPERATION_EXTERNAL_LIBM_LONG_EXPONENT_IN, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_scalblnl", FLOATING_INTRINSIC_SCALBLNL,
		FLOATING_OPERATION_EXTERNAL_LIBM_LONG_EXPONENT_IN, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_scalbn", FLOATING_INTRINSIC_SCALBN,
		FLOATING_OPERATION_EXTERNAL_LIBM_EXPONENT_IN, FLOATING_FORMAT_DOUBLE, 2},
	{"__builtin_scalbnf", FLOATING_INTRINSIC_SCALBNF,
		FLOATING_OPERATION_EXTERNAL_LIBM_EXPONENT_IN, FLOATING_FORMAT_FLOAT, 2},
	{"__builtin_scalbnl", FLOATING_INTRINSIC_SCALBNL,
		FLOATING_OPERATION_EXTERNAL_LIBM_EXPONENT_IN, FLOATING_FORMAT_LONG_DOUBLE, 2},
	{"__builtin_signbit", FLOATING_INTRINSIC_SIGNBIT,
		FLOATING_OPERATION_SIGNBIT, FLOATING_FORMAT_NONE, 1},
	{"__builtin_sin", FLOATING_INTRINSIC_SIN,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_sinf", FLOATING_INTRINSIC_SINF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_sinh", FLOATING_INTRINSIC_SINH,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_sinhf", FLOATING_INTRINSIC_SINHF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_sinhl", FLOATING_INTRINSIC_SINHL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_sinl", FLOATING_INTRINSIC_SINL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_sqrt", FLOATING_INTRINSIC_SQRT,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_sqrtf", FLOATING_INTRINSIC_SQRTF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_sqrtl", FLOATING_INTRINSIC_SQRTL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_tan", FLOATING_INTRINSIC_TAN,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_tanf", FLOATING_INTRINSIC_TANF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_tanh", FLOATING_INTRINSIC_TANH,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_tanhf", FLOATING_INTRINSIC_TANHF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_tanhl", FLOATING_INTRINSIC_TANHL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_tanl", FLOATING_INTRINSIC_TANL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_tgamma", FLOATING_INTRINSIC_TGAMMA,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_tgammaf", FLOATING_INTRINSIC_TGAMMAF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_tgammal", FLOATING_INTRINSIC_TGAMMAL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1},
	{"__builtin_trunc", FLOATING_INTRINSIC_TRUNC,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_DOUBLE, 1},
	{"__builtin_truncf", FLOATING_INTRINSIC_TRUNCF,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_FLOAT, 1},
	{"__builtin_truncl", FLOATING_INTRINSIC_TRUNCL,
		FLOATING_OPERATION_EXTERNAL_LIBM, FLOATING_FORMAT_LONG_DOUBLE, 1}
};

const MemoryIntrinsic kMemoryIntrinsics[] = {
	{"__builtin_assume_aligned", MEMORY_INTRINSIC_ASSUME_ALIGNED, 2, 3,
		MEMORY_EFFECT_READNONE, MEMORY_LOWER_IDENTITY},
	{"__builtin_bzero", MEMORY_INTRINSIC_BZERO, 2, 2,
		MEMORY_EFFECT_READWRITE, MEMORY_LOWER_EXTERNAL},
	{"__builtin_memchr", MEMORY_INTRINSIC_MEMCHR, 3, 3,
		MEMORY_EFFECT_READONLY, MEMORY_LOWER_EXTERNAL},
	{"__builtin_memcmp", MEMORY_INTRINSIC_MEMCMP, 3, 3,
		MEMORY_EFFECT_READONLY, MEMORY_LOWER_EXTERNAL},
	{"__builtin_memcpy", MEMORY_INTRINSIC_MEMCPY, 3, 3,
		MEMORY_EFFECT_READWRITE, MEMORY_LOWER_EXTERNAL},
	{"__builtin_memmove", MEMORY_INTRINSIC_MEMMOVE, 3, 3,
		MEMORY_EFFECT_READWRITE, MEMORY_LOWER_EXTERNAL},
	{"__builtin_memset", MEMORY_INTRINSIC_MEMSET, 3, 3,
		MEMORY_EFFECT_READWRITE, MEMORY_LOWER_EXTERNAL},
	{"__builtin_prefetch", MEMORY_INTRINSIC_PREFETCH, 1, 3,
		MEMORY_EFFECT_READNONE, MEMORY_LOWER_NOOP},
	{"__builtin_strchr", MEMORY_INTRINSIC_STRCHR, 2, 2,
		MEMORY_EFFECT_READONLY, MEMORY_LOWER_EXTERNAL},
	{"__builtin_strcmp", MEMORY_INTRINSIC_STRCMP, 2, 2,
		MEMORY_EFFECT_READONLY, MEMORY_LOWER_EXTERNAL},
	{"__builtin_strlen", MEMORY_INTRINSIC_STRLEN, 1, 1,
		MEMORY_EFFECT_READONLY, MEMORY_LOWER_EXTERNAL}
};

const VectorIntrinsic kVectorIntrinsics[] = {
	{"__builtin_ia32_vec_ext_v2si", VECTOR_INTRINSIC_IA32_VEC_EXT_V2SI,
		VECTOR_OPERATION_EXTRACT, VECTOR_ELEMENT_I32, 2},
	{"__builtin_ia32_vec_init_v2si",
		VECTOR_INTRINSIC_IA32_VEC_INIT_V2SI,
		VECTOR_OPERATION_INIT, VECTOR_ELEMENT_I32, 2},
	{"__builtin_ia32_vec_init_v4hi",
		VECTOR_INTRINSIC_IA32_VEC_INIT_V4HI,
		VECTOR_OPERATION_INIT, VECTOR_ELEMENT_I16, 4},
	{"__builtin_ia32_vec_init_v8qi",
		VECTOR_INTRINSIC_IA32_VEC_INIT_V8QI,
		VECTOR_OPERATION_INIT, VECTOR_ELEMENT_I8, 8}
};

const AtomicIntrinsic kAtomicIntrinsics[] = {
	{"__atomic_add_fetch", ATOMIC_INTRINSIC_ADD_FETCH,
		ATOMIC_SHAPE_FETCH_UPDATE, ATOMIC_UPDATE_ADD, 3, true, false},
	{"__atomic_always_lock_free", ATOMIC_INTRINSIC_ALWAYS_LOCK_FREE,
		ATOMIC_SHAPE_LOCK_FREE, ATOMIC_UPDATE_NONE, 2, false, false},
	{"__atomic_clear", ATOMIC_INTRINSIC_CLEAR,
		ATOMIC_SHAPE_CLEAR, ATOMIC_UPDATE_NONE, 2, false, false},
	{"__atomic_compare_exchange_n", ATOMIC_INTRINSIC_COMPARE_EXCHANGE_N,
		ATOMIC_SHAPE_COMPARE_EXCHANGE, ATOMIC_UPDATE_NONE, 6, false, false},
	{"__atomic_exchange_n", ATOMIC_INTRINSIC_EXCHANGE_N,
		ATOMIC_SHAPE_EXCHANGE, ATOMIC_UPDATE_NONE, 3, false, false},
	{"__atomic_fetch_add", ATOMIC_INTRINSIC_FETCH_ADD,
		ATOMIC_SHAPE_FETCH_UPDATE, ATOMIC_UPDATE_ADD, 3, false, false},
	{"__atomic_fetch_and", ATOMIC_INTRINSIC_FETCH_AND,
		ATOMIC_SHAPE_FETCH_UPDATE, ATOMIC_UPDATE_AND, 3, false, false},
	{"__atomic_fetch_or", ATOMIC_INTRINSIC_FETCH_OR,
		ATOMIC_SHAPE_FETCH_UPDATE, ATOMIC_UPDATE_OR, 3, false, false},
	{"__atomic_fetch_sub", ATOMIC_INTRINSIC_FETCH_SUB,
		ATOMIC_SHAPE_FETCH_UPDATE, ATOMIC_UPDATE_SUB, 3, false, false},
	{"__atomic_fetch_xor", ATOMIC_INTRINSIC_FETCH_XOR,
		ATOMIC_SHAPE_FETCH_UPDATE, ATOMIC_UPDATE_XOR, 3, false, false},
	{"__atomic_is_lock_free", ATOMIC_INTRINSIC_IS_LOCK_FREE,
		ATOMIC_SHAPE_LOCK_FREE, ATOMIC_UPDATE_NONE, 2, false, false},
	{"__atomic_load", ATOMIC_INTRINSIC_LOAD,
		ATOMIC_SHAPE_LOAD_OUT, ATOMIC_UPDATE_NONE, 3, false, false},
	{"__atomic_load_n", ATOMIC_INTRINSIC_LOAD_N,
		ATOMIC_SHAPE_LOAD, ATOMIC_UPDATE_NONE, 2, false, false},
	{"__atomic_signal_fence", ATOMIC_INTRINSIC_SIGNAL_FENCE,
		ATOMIC_SHAPE_FENCE, ATOMIC_UPDATE_NONE, 1, false, false},
	{"__atomic_store", ATOMIC_INTRINSIC_STORE,
		ATOMIC_SHAPE_STORE_FROM, ATOMIC_UPDATE_NONE, 3, false, false},
	{"__atomic_store_n", ATOMIC_INTRINSIC_STORE_N,
		ATOMIC_SHAPE_STORE, ATOMIC_UPDATE_NONE, 3, false, false},
	{"__atomic_test_and_set", ATOMIC_INTRINSIC_TEST_AND_SET,
		ATOMIC_SHAPE_TEST_AND_SET, ATOMIC_UPDATE_NONE, 2, false, false},
	{"__atomic_thread_fence", ATOMIC_INTRINSIC_THREAD_FENCE,
		ATOMIC_SHAPE_FENCE, ATOMIC_UPDATE_NONE, 1, false, false},
	{"__c11_atomic_compare_exchange_strong",
		ATOMIC_INTRINSIC_C11_COMPARE_EXCHANGE_STRONG,
		ATOMIC_SHAPE_COMPARE_EXCHANGE, ATOMIC_UPDATE_NONE, 5, false, true},
	{"__c11_atomic_compare_exchange_weak",
		ATOMIC_INTRINSIC_C11_COMPARE_EXCHANGE_WEAK,
		ATOMIC_SHAPE_COMPARE_EXCHANGE, ATOMIC_UPDATE_NONE, 5, false, true},
	{"__c11_atomic_exchange", ATOMIC_INTRINSIC_C11_EXCHANGE,
		ATOMIC_SHAPE_EXCHANGE, ATOMIC_UPDATE_NONE, 3, false, true},
	{"__c11_atomic_fetch_add", ATOMIC_INTRINSIC_C11_FETCH_ADD,
		ATOMIC_SHAPE_FETCH_UPDATE, ATOMIC_UPDATE_ADD, 3, false, true},
	{"__c11_atomic_fetch_and", ATOMIC_INTRINSIC_C11_FETCH_AND,
		ATOMIC_SHAPE_FETCH_UPDATE, ATOMIC_UPDATE_AND, 3, false, true},
	{"__c11_atomic_fetch_or", ATOMIC_INTRINSIC_C11_FETCH_OR,
		ATOMIC_SHAPE_FETCH_UPDATE, ATOMIC_UPDATE_OR, 3, false, true},
	{"__c11_atomic_fetch_sub", ATOMIC_INTRINSIC_C11_FETCH_SUB,
		ATOMIC_SHAPE_FETCH_UPDATE, ATOMIC_UPDATE_SUB, 3, false, true},
	{"__c11_atomic_fetch_xor", ATOMIC_INTRINSIC_C11_FETCH_XOR,
		ATOMIC_SHAPE_FETCH_UPDATE, ATOMIC_UPDATE_XOR, 3, false, true},
	{"__c11_atomic_init", ATOMIC_INTRINSIC_C11_INIT,
		ATOMIC_SHAPE_STORE, ATOMIC_UPDATE_NONE, 2, false, true},
	{"__c11_atomic_is_lock_free", ATOMIC_INTRINSIC_C11_IS_LOCK_FREE,
		ATOMIC_SHAPE_LOCK_FREE, ATOMIC_UPDATE_NONE, 1, false, false},
	{"__c11_atomic_load", ATOMIC_INTRINSIC_C11_LOAD,
		ATOMIC_SHAPE_LOAD, ATOMIC_UPDATE_NONE, 2, false, true},
	{"__c11_atomic_signal_fence", ATOMIC_INTRINSIC_C11_SIGNAL_FENCE,
		ATOMIC_SHAPE_FENCE, ATOMIC_UPDATE_NONE, 1, false, false},
	{"__c11_atomic_store", ATOMIC_INTRINSIC_C11_STORE,
		ATOMIC_SHAPE_STORE, ATOMIC_UPDATE_NONE, 3, false, true},
	{"__c11_atomic_thread_fence", ATOMIC_INTRINSIC_C11_THREAD_FENCE,
		ATOMIC_SHAPE_FENCE, ATOMIC_UPDATE_NONE, 1, false, false},
	{"__sync_fetch_and_add", ATOMIC_INTRINSIC_SYNC_FETCH_AND_ADD,
		ATOMIC_SHAPE_FETCH_UPDATE, ATOMIC_UPDATE_ADD, 2, false, false},
	{"__sync_lock_release", ATOMIC_INTRINSIC_SYNC_LOCK_RELEASE,
		ATOMIC_SHAPE_CLEAR, ATOMIC_UPDATE_NONE, 1, false, false},
	{"__sync_lock_test_and_set", ATOMIC_INTRINSIC_SYNC_LOCK_TEST_AND_SET,
		ATOMIC_SHAPE_EXCHANGE, ATOMIC_UPDATE_NONE, 2, false, false},
	{"__sync_synchronize", ATOMIC_INTRINSIC_SYNC_SYNCHRONIZE,
		ATOMIC_SHAPE_FENCE, ATOMIC_UPDATE_NONE, 0, false, false},
	{"__sync_val_compare_and_swap", ATOMIC_INTRINSIC_SYNC_VAL_COMPARE_AND_SWAP,
		ATOMIC_SHAPE_SYNC_COMPARE_EXCHANGE, ATOMIC_UPDATE_NONE, 3, false, false}
};

template <class Kind>
struct Entry
{
	const char* spelling;
	Kind kind;
};

template <class Kind, std::size_t Size>
Kind FindEntry(const std::string& spelling, const Entry<Kind> (&entries)[Size],
	Kind missing)
{
	std::size_t first = 0;
	std::size_t count = Size;
	while (first < count)
	{
		const std::size_t middle = first + (count - first) / 2;
		const int order = spelling.compare(entries[middle].spelling);
		if (order < 0) count = middle;
		else if (order > 0) first = middle + 1;
		else return entries[middle].kind;
	}
	return missing;
}

}

TypeTraitKind FindTypeTrait(const std::string& spelling)
{
	static const Entry<TypeTraitKind> entries[] = {
		{"__array_rank", TYPE_TRAIT_ARRAY_RANK},
		{"__has_nothrow_copy", TYPE_TRAIT_HAS_NOTHROW_COPY},
		{"__has_trivial_constructor", TYPE_TRAIT_HAS_TRIVIAL_CONSTRUCTOR},
		{"__has_trivial_destructor", TYPE_TRAIT_IS_TRIVIALLY_DESTRUCTIBLE},
		{"__has_virtual_destructor", TYPE_TRAIT_HAS_VIRTUAL_DESTRUCTOR},
		{"__is_abstract", TYPE_TRAIT_IS_ABSTRACT},
		{"__is_aggregate", TYPE_TRAIT_IS_AGGREGATE},
		{"__is_arithmetic", TYPE_TRAIT_IS_ARITHMETIC},
		{"__is_array", TYPE_TRAIT_IS_ARRAY},
		{"__is_assignable", TYPE_TRAIT_IS_ASSIGNABLE},
		{"__is_base_of", TYPE_TRAIT_IS_BASE_OF},
		{"__is_bounded_array", TYPE_TRAIT_IS_BOUNDED_ARRAY},
		{"__is_class", TYPE_TRAIT_IS_CLASS},
		{"__is_complete_or_unbounded", TYPE_TRAIT_IS_COMPLETE_OR_UNBOUNDED},
		{"__is_compound", TYPE_TRAIT_IS_COMPOUND},
		{"__is_const", TYPE_TRAIT_IS_CONST},
		{"__is_constructible", TYPE_TRAIT_IS_CONSTRUCTIBLE},
		{"__is_convertible", TYPE_TRAIT_IS_CONVERTIBLE},
		{"__is_destructible", TYPE_TRAIT_IS_DESTRUCTIBLE},
		{"__is_empty", TYPE_TRAIT_IS_EMPTY},
		{"__is_enum", TYPE_TRAIT_IS_ENUM},
		{"__is_final", TYPE_TRAIT_IS_FINAL},
		{"__is_floating_point", TYPE_TRAIT_IS_FLOATING_POINT},
		{"__is_function", TYPE_TRAIT_IS_FUNCTION},
		{"__is_fundamental", TYPE_TRAIT_IS_FUNDAMENTAL},
		{"__is_integral", TYPE_TRAIT_IS_INTEGRAL},
		{"__is_invocable", TYPE_TRAIT_IS_INVOCABLE},
		{"__is_literal_type", TYPE_TRAIT_IS_LITERAL_TYPE},
		{"__is_lvalue_reference", TYPE_TRAIT_IS_LVALUE_REFERENCE},
		{"__is_member_function_pointer", TYPE_TRAIT_IS_MEMBER_FUNCTION_POINTER},
		{"__is_member_object_pointer", TYPE_TRAIT_IS_MEMBER_OBJECT_POINTER},
		{"__is_member_pointer", TYPE_TRAIT_IS_MEMBER_POINTER},
		{"__is_nothrow_assignable", TYPE_TRAIT_IS_NOTHROW_ASSIGNABLE},
		{"__is_nothrow_constructible", TYPE_TRAIT_IS_NOTHROW_CONSTRUCTIBLE},
		{"__is_nothrow_invocable", TYPE_TRAIT_IS_NOTHROW_INVOCABLE},
		{"__is_object", TYPE_TRAIT_IS_OBJECT},
		{"__is_pod", TYPE_TRAIT_IS_POD},
		{"__is_pointer", TYPE_TRAIT_IS_POINTER},
		{"__is_polymorphic", TYPE_TRAIT_IS_POLYMORPHIC},
		{"__is_reference", TYPE_TRAIT_IS_REFERENCE},
		{"__is_referenceable", TYPE_TRAIT_IS_REFERENCEABLE},
		{"__is_rvalue_reference", TYPE_TRAIT_IS_RVALUE_REFERENCE},
		{"__is_same", TYPE_TRAIT_IS_SAME},
		{"__is_scalar", TYPE_TRAIT_IS_SCALAR},
		{"__is_signed", TYPE_TRAIT_IS_SIGNED},
		{"__is_standard_layout", TYPE_TRAIT_IS_STANDARD_LAYOUT},
		{"__is_trivial", TYPE_TRAIT_IS_TRIVIAL},
		{"__is_trivially_assignable", TYPE_TRAIT_IS_TRIVIALLY_ASSIGNABLE},
		{"__is_trivially_constructible", TYPE_TRAIT_IS_TRIVIALLY_CONSTRUCTIBLE},
		{"__is_trivially_copyable", TYPE_TRAIT_IS_TRIVIALLY_COPYABLE},
		{"__is_trivially_destructible", TYPE_TRAIT_IS_TRIVIALLY_DESTRUCTIBLE},
		{"__is_unbounded_array", TYPE_TRAIT_IS_UNBOUNDED_ARRAY},
		{"__is_union", TYPE_TRAIT_IS_UNION},
		{"__is_unsigned", TYPE_TRAIT_IS_UNSIGNED},
		{"__is_void", TYPE_TRAIT_IS_VOID},
		{"__is_volatile", TYPE_TRAIT_IS_VOLATILE},
		{"__reference_binds_to_temporary", TYPE_TRAIT_REFERENCE_BINDS_TO_TEMPORARY},
		{"__reference_constructs_from_temporary", TYPE_TRAIT_REFERENCE_CONSTRUCTS_FROM_TEMPORARY}
	};
	return FindEntry(spelling, entries, TYPE_TRAIT_NONE);
}

TypeTransformKind FindTypeTransform(const std::string& spelling)
{
	static const Entry<TypeTransformKind> entries[] = {
		{"__add_lvalue_reference", TYPE_TRANSFORM_ADD_LVALUE_REFERENCE},
		{"__add_pointer", TYPE_TRANSFORM_ADD_POINTER},
		{"__add_rvalue_reference", TYPE_TRANSFORM_ADD_RVALUE_REFERENCE},
		{"__decay", TYPE_TRANSFORM_DECAY},
		{"__make_signed", TYPE_TRANSFORM_MAKE_SIGNED},
		{"__make_unsigned", TYPE_TRANSFORM_MAKE_UNSIGNED},
		{"__remove_all_extents", TYPE_TRANSFORM_REMOVE_ALL_EXTENTS},
		{"__remove_const", TYPE_TRANSFORM_REMOVE_CONST},
		{"__remove_cv", TYPE_TRANSFORM_REMOVE_CV},
		{"__remove_cvref", TYPE_TRANSFORM_REMOVE_CVREF},
		{"__remove_pointer", TYPE_TRANSFORM_REMOVE_POINTER},
		{"__remove_reference_t", TYPE_TRANSFORM_REMOVE_REFERENCE},
		{"__remove_volatile", TYPE_TRANSFORM_REMOVE_VOLATILE},
		{"__underlying_type", TYPE_TRANSFORM_UNDERLYING_TYPE}
	};
	return FindEntry(spelling, entries, TYPE_TRANSFORM_NONE);
}

const IntegerIntrinsic* FindIntegerIntrinsic(const std::string& spelling)
{
	std::size_t first = 0;
	std::size_t count = sizeof(kIntegerIntrinsics) /
		sizeof(kIntegerIntrinsics[0]);
	while (first < count)
	{
		const std::size_t middle = first + (count - first) / 2;
		const int order = spelling.compare(kIntegerIntrinsics[middle].spelling);
		if (order < 0) count = middle;
		else if (order > 0) first = middle + 1;
		else return &kIntegerIntrinsics[middle];
	}
	return 0;
}

const IntegerIntrinsic& GetIntegerIntrinsic(IntegerIntrinsicKind kind)
{
	if (kind <= INTEGER_INTRINSIC_NONE || kind >= INTEGER_INTRINSIC_COUNT)
		ThrowInternalCompilerError("invalid hosted integer intrinsic kind");
	return kIntegerIntrinsics[static_cast<std::size_t>(kind) - 1];
}

const FloatingIntrinsic* FindFloatingIntrinsic(const std::string& spelling)
{
	std::size_t first = 0;
	std::size_t count = sizeof(kFloatingIntrinsics) /
		sizeof(kFloatingIntrinsics[0]);
	while (first < count)
	{
		const std::size_t middle = first + (count - first) / 2;
		const int order = spelling.compare(kFloatingIntrinsics[middle].spelling);
		if (order < 0) count = middle;
		else if (order > 0) first = middle + 1;
		else return &kFloatingIntrinsics[middle];
	}
	return 0;
}

const FloatingIntrinsic& GetFloatingIntrinsic(FloatingIntrinsicKind kind)
{
	if (kind <= FLOATING_INTRINSIC_NONE || kind >= FLOATING_INTRINSIC_COUNT)
		ThrowInternalCompilerError("invalid hosted floating intrinsic kind");
	return kFloatingIntrinsics[static_cast<std::size_t>(kind) - 1];
}

const MemoryIntrinsic* FindMemoryIntrinsic(const std::string& spelling)
{
	std::size_t first = 0;
	std::size_t count = sizeof(kMemoryIntrinsics) /
		sizeof(kMemoryIntrinsics[0]);
	while (first < count)
	{
		const std::size_t middle = first + (count - first) / 2;
		const int order = spelling.compare(kMemoryIntrinsics[middle].spelling);
		if (order < 0) count = middle;
		else if (order > 0) first = middle + 1;
		else return &kMemoryIntrinsics[middle];
	}
	return 0;
}

const MemoryIntrinsic& GetMemoryIntrinsic(MemoryIntrinsicKind kind)
{
	if (kind <= MEMORY_INTRINSIC_NONE || kind >= MEMORY_INTRINSIC_COUNT)
		ThrowInternalCompilerError("invalid hosted memory intrinsic kind");
	return kMemoryIntrinsics[static_cast<std::size_t>(kind) - 1];
}

const VectorIntrinsic* FindVectorIntrinsic(const std::string& spelling)
{
	std::size_t first = 0;
	std::size_t count = sizeof(kVectorIntrinsics) /
		sizeof(kVectorIntrinsics[0]);
	while (first < count)
	{
		const std::size_t middle = first + (count - first) / 2;
		const int order = spelling.compare(kVectorIntrinsics[middle].spelling);
		if (order < 0) count = middle;
		else if (order > 0) first = middle + 1;
		else return &kVectorIntrinsics[middle];
	}
	return 0;
}

const VectorIntrinsic& GetVectorIntrinsic(VectorIntrinsicKind kind)
{
	if (kind <= VECTOR_INTRINSIC_NONE || kind >= VECTOR_INTRINSIC_COUNT)
		ThrowInternalCompilerError("invalid hosted vector intrinsic kind");
	return kVectorIntrinsics[static_cast<std::size_t>(kind) - 1];
}

const AtomicIntrinsic* FindAtomicIntrinsic(const std::string& spelling)
{
	std::size_t first = 0;
	std::size_t count = sizeof(kAtomicIntrinsics) /
		sizeof(kAtomicIntrinsics[0]);
	while (first < count)
	{
		const std::size_t middle = first + (count - first) / 2;
		const int order = spelling.compare(kAtomicIntrinsics[middle].spelling);
		if (order < 0) count = middle;
		else if (order > 0) first = middle + 1;
		else return &kAtomicIntrinsics[middle];
	}
	return 0;
}

const AtomicIntrinsic& GetAtomicIntrinsic(AtomicIntrinsicKind kind)
{
	if (kind <= ATOMIC_INTRINSIC_NONE || kind >= ATOMIC_INTRINSIC_COUNT)
		ThrowInternalCompilerError("invalid hosted atomic intrinsic kind");
	return kAtomicIntrinsics[static_cast<std::size_t>(kind) - 1];
}

}
}
