struct Level0 { int value; };
struct Level1 { Level0 a, b; };
struct Level2 { Level1 a, b; };
struct Level3 { Level2 a, b; };
struct Level4 { Level3 a, b; };
struct Level5 { Level4 a, b; };
struct Level6 { Level5 a, b; };
struct Level7 { Level6 a, b; };
struct Level8 { Level7 a, b; };
struct Level9 { Level8 a, b; };
struct Level10 { Level9 a, b; };
struct Level11 { Level10 a, b; };
struct Level12 { Level11 a, b; };
struct Level13 { Level12 a, b; };
struct Level14 { Level13 a, b; };
struct Level15 { Level14 a, b; };
struct Level16 { Level15 a, b; };
struct Level17 { Level16 a, b; };
struct Level18 { Level17 a, b; };
static_assert(__is_trivially_copyable(Level18), "nested declaration graph");
struct DeletedLeaf { DeletedLeaf(const DeletedLeaf&) = delete; DeletedLeaf& operator=(const DeletedLeaf&) = delete; };

struct DeletedLevel1 { DeletedLeaf a, b; };
struct DeletedLevel2 { DeletedLevel1 a, b; };
struct DeletedLevel3 { DeletedLevel2 a, b; };
struct DeletedLevel4 { DeletedLevel3 a, b; };
struct DeletedLevel5 { DeletedLevel4 a, b; };
struct DeletedLevel6 { DeletedLevel5 a, b; };
struct DeletedLevel7 { DeletedLevel6 a, b; };
struct DeletedLevel8 { DeletedLevel7 a, b; };
struct DeletedLevel9 { DeletedLevel8 a, b; };
struct DeletedLevel10 { DeletedLevel9 a, b; };
struct DeletedLevel11 { DeletedLevel10 a, b; };
struct DeletedLevel12 { DeletedLevel11 a, b; };
struct DeletedLevel13 { DeletedLevel12 a, b; };
struct DeletedLevel14 { DeletedLevel13 a, b; };
struct DeletedLevel15 { DeletedLevel14 a, b; };
struct DeletedLevel16 { DeletedLevel15 a, b; };
struct DeletedLevel17 { DeletedLevel16 a, b; };
struct DeletedLevel18 { DeletedLevel17 a, b; };
static_assert(__is_trivially_copyable(DeletedLevel18), "shared deleted declaration graph");
int main() { return 0; }
